# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

gem "middleman", "~>3.3"
gem "middleman-deploy"
gem "middleman-blog", "~> 3.5"
gem "middleman-blog-drafts"
gem "middleman-autometatags"
gem "middleman-livereload", "~> 3.1.0"
gem 'middleman-bootstrap-navbar'

gem "bootstrap-sass"
gem "jquery-middleman"

# For faster file watcher updates on Windows:
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Windows does not come with time zone data
gem "tzinfo-data", platforms: [:mswin, :mingw]

gem "builder", "~> 3.0"

