# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94dd413b6a186116fdde2d5d10d17d2e50a103a8de01b6dcd305e6d4ccc44b369b558224d33ce6c680e83e41332d398383a3eef2a4ad87a2095b9f275af9738

test:
  secret_key_base: 54218459a46d04d45842a43f1508c9892a51ea5e51df193c7d8320310909e44343a7b835be999c3df65471d6a1a22b8e2b9234a698926528875fa3bf33df1609

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
